# Generated by Django 6.0.1 on 2026-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warzywa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.PositiveIntegerField()),
                ('czy_bio', models.BooleanField(default=True)),
            ],
        ),
    ]
