# Generated by Django 6.0.1 on 2026-01-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.PositiveIntegerField()),
                ('czy_bio', models.BooleanField(default=True)),
                ('rodzaj', models.CharField(help_text='np. Wołowina, Drób', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Napoje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.PositiveIntegerField()),
                ('czy_bio', models.BooleanField(default=True)),
                ('objetosc', models.FloatField(help_text='w litrach, np. 0.5')),
                ('czy_gazowany', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.PositiveIntegerField()),
                ('czy_bio', models.BooleanField(default=True)),
                ('czy_suszone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pieczywo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.PositiveIntegerField()),
                ('czy_bio', models.BooleanField(default=True)),
                ('rodzaj_maki', models.CharField(help_text='np. Żytnia, Pszenna', max_length=100)),
            ],
        ),
    ]
